app.common.init();
app.map.reloadBaseVh();
app.sliderServices.init();
app.map.mapLoading();
app.feed.openItem();
app.nav.eventStyle();
app.map.eventListControl();
app.map.scrollEventList();
app.map.scrollEventListResize();
